
server:
  port: 3355

spring:
  application:
#   这个名字很重要，是注册到注册中心必须用到的，也是服务发现时用到的名字。并且必须要对外显露统一的服务实例名称，不能更改。
    name: microservice-config-client

eureka:
  # 客户端注册进 eureka 服务列表内
  client:
    service-url:
      # 单机版，只有一个注册中心时
      # defaultZone: http://localhost:7001/eureka
      # 集群版，同时有多个注册中心时
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
    # 自定义在注册中心页面显示的微服务的名称
    instance-id: config-client-3355
    # 设置显示微服务名称链接的访问路径 IP 地址
    prefer-ip-address: true