
server:
  port: 7003


# 集群模式
eureka:
  client:
    service-url:
      # http://localhost:7001/eureka，设置与 eureka server 交互的地址，查询服务和注册服务都需要这个地址
       defaultZone: http://admin:admin@eureka7001:7001/eureka/, http://eureka7002:7002/eureka/
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
  instance:
    # 自定义要使用的主机名，用于客户端访问。注意一定要修改 host 文件，增加注册中心与本机的映射（127.0.0.1 eureka7003）
    hostname: eureka7003
#  server:
    # 禁用自我保护模式
#    enable-self-preservation: false
