server:
  port: 7001

eureka:
  client:
    service-url:
      # http://localhost:7001/eureka，设置与 eureka server 交互的地址，查询服务和注册服务都需要这个地址
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
  instance:
    # eureka 服务端的实例名称
    hostname: localhost

