
# 如果是要打印 feign 的日志，则最低是 debug 级别，并且必须要配置在 FeignClient 服务端，且在 FeignClient 指定的配置类中声明了
# 日志输出，否则不会输出日志。
# 可以对每个 feignClient 进行配置。
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

    # 如果需要对提供者中的类打印日志，则必须在该类指定的 FeignClient 指定的配置类中声明了日志输出 bean，否则不会打印日志
    com.hyman.providerdepthystrix8001.controller.DeptController: debug


# feign 对 request or response 的 GZIP 压缩
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
