server:
  port: 3355

spring:
  application:
    # 这个名字很重要，是注册到注册中心必须用到的，也是服务发现时用到的名字。并且必须要对外显露统一的服务实例名称，不能更改。
    name: microservice-config-client-bus
  # 设置上传文件大小
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


# 但对于大型文件，可以使用 /zuul/*，该路径会绕过 Spring DispatcherServlet 来进行文件上传（因为通常所有的请求都会被主控制器接收并分配）。
# 即在使用 zuul 进行转发本服务进行文件上传时，可使用 zuulIP:port/zuul/本服务application-name（或自定义的映射路径）/uploadpath 即可。
# 换句话说，如果您有zuul.routes.customers=/customers/**，那么您可以将大文件发布到/zuul/customers/*。servlet路径通过zuul.servlet path外部化。如果代理路由带您通过功能区负载平衡器，则超大文件还需要提升超时设置


eureka:
  # 客户端注册进 eureka 服务列表内
  client:
    service-url:
      # 单机版，只有一个注册中心时
      # defaultZone: http://localhost:7001/eureka
      # 集群版，同时有多个注册中心时
      defaultZone: http://admin:admin@eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
    # 自定义在注册中心页面显示的微服务的名称
    instance-id: config-client-bus-3356
    # 设置显示微服务名称链接的访问路径 IP 地址
    prefer-ip-address: true


# 通过配置文件指定提供者的负载均衡算法，而不再需要进行编码。
# 优先级为：配置文件 》 RibbonClient 注解代码 》 cloud 默认的配置。
microservice-config-dept-client:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

