
server:
  port: 7001


#设置eurekaServer的登录密码:
  security:
    user:
      name: admin  # 用户名
      password: admin   # 用户密码
  redis:
    lettuce:
      shutdown-timeout:

# nacos 集群地址
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

# nacos 单机服务器地址
#nacos:
#  discovery:
#    server-addr: 127.0.0.1:8848


logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.hyman.cloudeureka7001.FeignController: debug
#    com.hyman.xxx: OFF

